LIVE_SENSORS :=  106 107 101 100 99 93 92 58 75 88 79 61 54 72 73 71 62 59 60 49 42 41 40

# syntax: option to `find` command
MAX_AGE_TO_CACHE := -mmin +30

# syntax: option to `date` command
# NOTE: Do NOT forget the single quotes below!
PLOT_SINCE := '30 days ago'

# in px
CONFIG_WIDTH_SMALL := 480
CONFIG_HEIGHT_SMALL := 200

CONFIG_WIDTH_BIG := 1024
CONFIG_HEIGHT_BIG := 600

CONFIG_WIDTH_ALL := 1024
CONFIG_HEIGHT_ALL := 768

# long and short version of graph timezone (server local TZ does NOT matter)
CONFIG_TIMEZONE := 'America/New_York'
CONFIG_TZ := 'EDT'

#PUBLISH_CMD := rsync -HavPS --exclude=/.run --delete-excluded --delete out/ WEBSERVER:DIRECTORY/
#VIEW_CMD := firefox out/index.html